# 1. Create a 3x3x3 array with random values 

In [ ]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[3,4,5],[6,7,8]],[[2,3,4],[4,5,6],[5,6,7]]])
print(a,a.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [3 4 5]
  [6 7 8]]

 [[2 3 4]
  [4 5 6]
  [5 6 7]]] (3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
aa=np.zeros((5,5))
for i in range(5):
    aa[i,i-1]=i
print(aa)    

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
a=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2==0:
            a[i,j]=0
        else :
            a[i,j]=1
print(a)            


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

# 5.  How to find common values between two arrays?

In [ ]:
a1=np.array([1,2,3,4,45,67,77])
a2=np.array([2,66,7,8,9,0,55])
np.intersect1d(a1,a2)

array([2])

# 6.How to get the dates of yesterday, today and tomorrow?

In [3]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [ ]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=(a==b)
print(c.all())

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
q=np.array([57,400,300,495,588,9,78])
max(q)
q[np.where(q==max(q))]=0

In [ ]:
print(q)

[ 57 400 300 495   0   9  78]


# 9. How to print all the values of an array?

In [ ]:
a=np.array([1,2,3,45,6])
print(a)

[ 1  2  3 45  6]


# 10.Subtract the mean of each row of a matrix

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=a.sum(axis=1)
b=b/a.shape[1]

In [ ]:
for i in range(len(a)):
    a[i,:]=a[i,:]-b[i]
a  

array([[-1,  0,  1],
       [-1,  0,  1]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [ ]:
a=np.array([1,2,3,45,56,2,2,2,2,2,1,5,5,3,3,3])
np.bincount(a).argmax()

2

# 14.How to get the n largest values of an array

In [ ]:
a=np.array([123,543,456,3,23,6543,2345])
a=np.sort(a)
n=int(input())
q=a[-n:]
print(q[::-1])

4
[6543 2345  543  456]


# 15.How to create a record array from a regular array?