In [61]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn import preprocessing

In [62]:
data = pd.read_csv("D:/letsupgrade/data/train.csv")

In [63]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [64]:
le= preprocessing.LabelEncoder()

In [65]:
data.Sex = le.fit_transform(data.Sex)

In [66]:
data.Embarked= le.fit_transform(data.Embarked)

In [183]:
pred = data.drop(["Name","Ticket","Cabin","PassengerId"],axis=1)

In [68]:
pred.head()

Survived  Pclass  Sex   Age  SibSp     Fare  Embarked
0         0       3    1  22.0      1   7.2500         2
1         1       1    0  38.0      1  71.2833         0
2         1       3    0  26.0      0   7.9250         2
3         1       1    0  35.0      1  53.1000         2
4         0       3    1  35.0      0   8.0500         2

In [69]:
pred.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Fare        0
Embarked    0
dtype: int64

In [219]:
coll=pred.columns
coll

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [215]:
pred.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [231]:
for i in range(8):
    if i==3 or i==6:
        continue
    x= pred.drop(coll[i],axis=1)
    y= pred.iloc[:,i]
    X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 0)
    ypred = baNB.fit(X_train,y_train).predict(X_test)
    print(coll[i],accuracy_score(y_test,ypred))
    print(confusion_matrix(y_test,ypred))
    print()
          
    
        

Survived 0.7715355805243446
[[131  26]
 [ 35  75]]

Pclass 0.5917602996254682
[[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]

Sex 0.7453183520599251
[[ 49  49]
 [ 19 150]]

SibSp 0.6891385767790262
[[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]

Parch 0.7153558052434457
[[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0   0]]

Embarked 0.7340823970037453
[[  0   0  49]
 [  0   0  22]
 [  0   0 196]]



it is best data for Survived feature preduction because it has more accuracy 